linters:
 flake8:
 eslint:
   config: "./eslint.config"
 csslint:
   ignore: 'box-model,box-sizing,important,ids,known-properties,order-alphabetical' 
files:
 ignore:
   - "src/generated/*"
   - "webroot/bower_components/*"